### PR TITLE
ML and DL Articles Added

### PR DESCRIPTION
**Pull request by hmd0404-nitk-eee**

### CODE REVIEW

**Review by tharun634 — CHANGES_REQUESTED** [review]
make the index alphabetical

**Comment by hmd0404-nitk-eee** [comment]
Hey! Sorry for the delay. I have incorporated all the requested changes.

**Review by tharun634 — CHANGES_REQUESTED** [review]
Sorry for the confusion, I just noticed something.
Shouldn't NN be inside ML and DL inside ML?
The file structure should look something like this

- IoT
- ML Folder
  - ML_ReadMe.md
  - NN Folder
    - NN_ReadMe.md
    - DL_Folder
      - DL_ReadMe.md

This will also help readers understand the hierarchy of ML, NN and DL

[reference image](https://miro.medium.com/max/1024/1*qN7WiClDdIs1n4iaz_McXQ.png)

**Comment by hmd0404-nitk-eee** [comment]
Are you sure NN outside DL. My articles kind of suggests other way round?

**Comment by hmd0404-nitk-eee** [comment]
Restructured all the files and folders as per given hierarchy.

**Pull request merged**
